format_version: v1.0
type: UniqueComponent
attributes: {id: spi0}
children:
- type: Symbols
  children:
  - type: Comment
    attributes: {id: SPI0_NVIC_ENABLE_COMMENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: SPI_CSR_INDEX}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: spi0, value: '0'}
  - type: Boolean
    attributes: {id: SPI_DRIVER_CONTROLLED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_spi_0, value: 'true'}
  - type: Boolean
    attributes: {id: SPI_EN_NPCS0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: spi0, value: 'true'}
  - type: Boolean
    attributes: {id: SPI_INTERRUPT_MODE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: spi0, value: 'true'}
  - type: KeyValueSet
    attributes: {id: SPI_MR_MSTR}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: SPI_MR_PCS}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: spi0, value: '4'}
  - type: Integer
    attributes: {id: SPI_NUM_CSR}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: spi0, value: '1'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: SPI0_SPI}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drv_spi_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: drv_spi_SPI_dependency}
- type: ElementPosition
  attributes: {x: '26', y: '225', id: spi0}
