format_version: v1.0
type: UniqueComponent
attributes: {id: FreeRTOS}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: FREERTOS_EXPECTED_IDLE_TIME_BEFORE_SLEEP}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Combo
    attributes: {id: FREERTOS_TICKLESS_IDLE_CHOICE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Tickless_Idle}
- type: ElementPosition
  attributes: {x: '30', y: '60', id: FreeRTOS}
