configName: sam_v71_xult_freertos
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAMV71Q21B
projectName: ''
settings:
  PackageFilter: bootloader;bsp;core;csp;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMV71_DFP\4.2.57\samv71b\atdf\ATSAMV71Q21B.atdf
