format_version: v1.0
type: GeneratorComponent
attributes: {id: drv_memory}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: DRV_MEMORY_COMMON_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_memory, value: Asynchronous}
      - type: User
        attributes: {value: Asynchronous}
  - type: Boolean
    attributes: {id: DRV_MEMORY_COMMON_SYS_TIME_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_memory, value: 'false'}
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: drv_memory}
    children:
    - type: Symbols
      children:
      - type: Integer
        attributes: {id: DRV_MEMORY_BUFFER_QUEUE_SIZE}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: '5'}
      - type: String
        attributes: {id: DRV_MEMORY_DEVICE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_memory_0, value: DRV_SST26}
      - type: Comment
        attributes: {id: DRV_MEMORY_DEVICE_COMMENT}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: text}
            children:
            - {type: Value, value: '*** Configure Memory Device in DRV_SST26 Configurations
                ***'}
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'true'}
      - type: Boolean
        attributes: {id: DRV_MEMORY_ERASE_ENABLE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_memory_0, value: 'true'}
      - type: Boolean
        attributes: {id: DRV_MEMORY_INTERRUPT_ENABLE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_memory_0, value: 'false'}
    - type: Attachments
      children:
      - type: DirectDependency
        attributes: {id: drv_memory_MEMORY_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: drv_sst26}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: memory}
  - type: InstanceComponent
    attributes: {instance: '1', id: drv_memory}
    children:
    - type: Symbols
      children:
      - type: Integer
        attributes: {id: DRV_MEMORY_BUFFER_QUEUE_SIZE}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: '5'}
      - type: String
        attributes: {id: DRV_MEMORY_DEVICE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_memory_1, value: EFC}
      - type: Comment
        attributes: {id: DRV_MEMORY_DEVICE_COMMENT}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: text}
            children:
            - {type: Value, value: '*** Configure Memory Device in EFC Configurations
                ***'}
      - type: Boolean
        attributes: {id: DRV_MEMORY_ERASE_ENABLE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_memory_1, value: 'true'}
      - type: Boolean
        attributes: {id: DRV_MEMORY_INTERRUPT_ENABLE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_memory_1, value: 'false'}
      - type: String
        attributes: {id: DRV_MEMORY_PLIB}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_memory_1, value: DRV_EFC}
      - type: File
        attributes: {id: DRV_MEMORY_PLIB_HEADER}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: name}
            children:
            - {type: Value, value: drv_memory_efc.h}
      - type: File
        attributes: {id: DRV_MEMORY_PLIB_SOURCE}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: name}
            children:
            - {type: Value, value: drv_memory_efc.c}
    - type: Attachments
      children:
      - type: DirectDependency
        attributes: {id: drv_memory_MEMORY_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: efc}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: EFC_MEMORY}
- type: ElementPosition
  attributes: {x: '350', y: '102', id: drv_memory}
