format_version: v1.0
type: UniqueComponent
attributes: {id: efc}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: DRV_MEMORY_CONNECTED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_memory_1, value: 'true'}
  - type: Integer
    attributes: {id: NVM_RWS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: efc, value: '6'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: EFC_MEMORY}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drv_memory_1}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: drv_memory_MEMORY_dependency}
- type: ElementPosition
  attributes: {x: '18', y: '230', id: efc}
