format_version: v1.0
type: UniqueComponent
attributes: {id: drv_at24}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: DRV_AT24_PLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_at24, value: TWIHS0}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: drv_at24_I2C_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: twihs0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: TWIHS0_I2C}
- type: ElementPosition
  attributes: {x: '357', y: '58', id: drv_at24}
